name: Generate Snake

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
     
      - uses: actions/checkout@v3

      - name: Ensure dist folder exists
        run: mkdir -p dist


      - uses: Platane/snk@v3
        with:
          github_user_name: Nosferatu0-alt
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake to output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          directory: dist
          force: true
